services:
  app:
    build: .
    image: post_aggregator
    depends_on:
      - migration
    # It's better to not restart this container automatically, due to tg limitations
    restart: no
    command: poetry run python -m aggregator
    environment:
      ENVIRONMENT: container
    networks:
      - local-network


  postgres:
    image: postgres:17.2
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: news_aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local-network


  migration:
    image: post_aggregator
    depends_on:
      - postgres
    command: alembic upgrade head
    environment:
      ENVIRONMENT: container
    networks:
      - local-network


volumes:
  postgres-data:

networks:
  local-network:
    name: local-network
