services:
  app:
    build: .
    image: post_aggregator
    restart: on-failure
    volumes:
      - "./:/app"
    command: poetry run python src/__main__.py
    environment:
      ENVIRONMENT: container
    networks:
      - local-network


  postgres:
    image: postgres:16.4
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: news_aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local-network


  migration:
    image: post_aggregator
    depends_on:
      - postgres
    command: alembic upgrade head
    volumes:
      - "./:/app"
    environment:
      ENVIRONMENT: container
    networks:
      - local-network


volumes:
  postgres-data:

networks:
  local-network:
    name: local-network
