version: "3.9"

services:
  app:
    build: .
    restart: on-failure
    volumes:
      - "./:/app"
    networks:
      - localstack-network

  postgres:
    image: postgres:16.2
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: news_aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - localstack-network

volumes:
  postgres-data:

networks:
  localstack-network:
    name: localstack-network
