"""init_v2

Revision ID: 5449fbd7e244
Revises: 
Create Date: 2024-12-25 14:23:56.622802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from aggregator.models import NOT_SPECIFIED_CHANNEL_TYPE

# revision identifiers, used by Alembic.
revision: str = '5449fbd7e244'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('channel_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type_', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('type_')
                    )
    op.create_table('channel',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('type_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['type_id'], ['channel_type.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('message',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('message_id', sa.Integer(), nullable=False),
                    sa.Column('grouped_id', sa.BigInteger(), nullable=True),
                    sa.Column('sent', sa.DateTime(), nullable=True),
                    sa.Column('channel_id', sa.BigInteger(), nullable=False),
                    sa.Column('original_channel_id', sa.BigInteger(), nullable=False),
                    sa.Column('original_message_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('original_channel_id', 'original_message_id', name='source_message_uniq')
                    )
    op.execute("INSERT INTO public.channel_type (id, type_)"
               f"VALUES (0, '{NOT_SPECIFIED_CHANNEL_TYPE}')")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('channel')
    op.drop_table('channel_type')
    # ### end Alembic commands ###
